### ISSUE TITLE
Add an option to clear clipboard after a certain period 

### ISSUE THREAD

**Issue by krishna8755** [TrianguloY/SimpleClipboardEditor#9]
Add an option the simple clipboard editor app to automatically clear clipboard data after a period set by the user.

**Comment by TrianguloY** [comment]
I'm sorry, but that's not possible. Android restricts the clipboard access to the current app only. As soon as you close the app, it cannot access the clipboard. This is also the reason that a 'history' feature is not possible (only for text present the moment the app opens).

The app provides a shortcut to clear it, that you can run as needed (this opens the app, clears the clipboard, and immediately closes it). But if you it to be cleared automatically...sorry but you need root for it (and in that case I'm sure there are better built-in rom modules to do so). 

:(

**Comment by krishna8755** [comment]
Ok. How about adding a quick panel shortcut for clearing clipboard. So that users can have a easier option to clear clipboard.

**Comment by TrianguloY** [comment]
Hmm, yes, that's easy. Valid suggestion. Please create a new issue with it!
